### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by freesoft0000** [slpcat/NT6xTweaking#1]
reg注册表文件大部分都是乱码

**Comment by slpcat** [comment]
使用git客户端克隆，不要直接zip下载

**Comment by freesoft0000** [comment]
恩。好的。
可是github上面的其他人做的注册表文件下载过来就没有出现乱码的情况。这是为什么呢。

**Comment by freesoft0000** [comment]
使用git克隆还是乱码
![2](https://user-images.githubusercontent.com/30435921/34975664-c5235ff8-fa8a-11e7-976e-34fcd883528e.png)

**Comment by slpcat** [comment]
编码已修复 全都改成utf8编码

**Comment by freesoft0000** [comment]
一样，还是乱码。
不知道你使用的是什么文档编辑器。
注册表不是全部是乱码，有个别编码是ansi的正常显示，编码是unicode的都是乱码。实在不行就都改成ansi的吧。单纯的转换应该无法正常显示。需要从新编辑正确的文件保存为ansi编码。

**Comment by slpcat** [comment]
英文的也改成UTF8了

**Comment by freesoft0000** [comment]
ok，随机的查看了一些，没有乱码情况了。
但是有部分注册表，注册表项没有和标头空开，少了一个空行，没有问题吧？按微软标准导出是有空行的。你的有部分内容没有空行，例如下面：
Windows Registry Editor Version 5.00
[HKEY_USERS\.DEFAULT\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize]
"AppsUseLightTheme"=dword:00000000
"SystemUsesLightTheme"=dword:00000000
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize]
"AppsUseLightTheme"=dword:00000000
"SystemUsesLightTheme"=dword:00000000
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize]
"AppsUseLightTheme"=dword:00000000
"SystemUsesLightTheme"=dword:00000000

**Comment by slpcat** [comment]
能导入就是没问题的
